<template>
	<div id="app">
		<main class="container">
			<section class="intro">
				<h1>Image Palette</h1>
				<p>
					Generate a color palette from an image and automatically
					pair each color with a
					<a
						href="https://w3c.github.io/wcag/understanding/contrast-minimum.html"
						>contrasting color</a
					>.
				</p>
				<p>
					The color palette is generated by
					<a href="https://github.com/akfish/node-vibrant/"
						>node-vibrant</a
					>, a Node.js implementation of
					<a
						href="https://developer.android.com/reference/android/support/v7/graphics/Palette.html"
						>Android's Palette class</a
					>. The contrasting color will be a color from the same
					palette if an accessible option is available. If not, it
					will be either black or white, depending on which one has a
					higher contrast ratio. In some rare instances, the resulting
					contrast ratio will be below the minimum threshold (4.5).
					These colors shouldn't be used with text in production.
				</p>
				<p>
					To get started, enter the URL to an image or press the
					random button to load an
					<a href="https://www.unsplash.com">Unsplash</a> image.
				</p>
			</section>
			<section class="demo">
				<div class="form-group">
					<label for="img-path">Image path (URL):</label>
					<div class="input-group mb-3">
						<input
							type="url"
							id="img-path"
							:class="[
								'form-control',
								{ 'is-invalid': inputFeedback },
							]"
							aria-describedby="input-feedback"
							v-model="inputUrl"
							@input="onInput"
						/>
						<div class="input-group-append">
							<button
								class="btn btn-outline-secondary rounded-right"
								type="button"
								@click="loadRandomUnsplash"
							>
								Random Unsplash
							</button>
						</div>
						<!-- <div class="input-group-append">
              <button class="btn btn-primary" type="button" @click="loadRandomNorton">Random Norton</button>
            </div>-->
						<div
							class="invalid-feedback"
							id="input-feedback"
							v-html="inputFeedback"
						></div>
					</div>
				</div>
				<vibrant-palette v-if="palette" :palette="palette" />
				<figure class="vibrant-figure" :style="dominantStyle">
					<div class="vibrant-img">
						<template>
							<img
								v-if="validImg"
								class="img-fluid"
								alt
								crossorigin="anonymous"
								:src="resolvedUrl"
								@load="processImage"
							/>
							<placeholder-block
								v-else
								class="img-fluid"
								:dimensions="dimensions"
							/>
						</template>
					</div>
					<!-- <div class="vibrant-gradient" :style="gradiantStyle"></div> -->
					<figcaption class="vibrant-caption">
						<p class="grid-align-start">
							Lorem ipsum dolor sit amet consectetur, adipisicing
							elit. Amet provident non totam quae numquam
							praesentium omnis ea dolorum. Dicta neque nostrum
							itaque modi consequuntur iusto non commodi labore
							repellendus et?
						</p>
						<button
							class="btn grid-justify-center grid-align-start"
							:style="inverseStyle"
							@click="copyLink"
						>
							Copy link to this palette
						</button>
					</figcaption>
				</figure>
				<div class="mb-4 d-flex justify-content-center">
					Created by Evan Yamanishi
					<svg
						xmlns="http://www.w3.org/2000/svg"
						viewBox="0 0 95 30"
						class="svg-seagull"
						role="img"
						aria-labelledby="svg-title"
					>
						<title id="svg-title">in the Norton Lab</title>
						<path
							fill="#2e445c"
							:style="seagullStyle"
							d="M28.06 22.47c.3-2 10.15-2.48 10.71-2.48 1.63 0 3.89-.13 1.81-.74a9 9 0 0 1-4.51-3.78 6.24 6.24 0 0 1-3.68-3c-2.21-.27-5.34-1.74-6.14-2.75A59.6 59.6 0 0 1 8 5.7C5.83 4.79-.64.44.05.21c2.11-.71 7.11.66 9.42.9 5.12.55 10.28.46 15.44.62h1.92c2.48-.07 5.37-.13 7.17 1.46 2.43 2.23 11.64 14.11 14 12.74.51-.31-.5-.77-1.66-1.13a.31.31 0 0 1 0-.59c5.11-1.18 8 1.88 14.4 2.74 5.28.7 5.89 3.61 5 6.53-.62 2.1.64 3.3 0 4.76-.34.76-.8.11-.88-.11-1.22-3.5-2.84-7.2-9.38-5a20.92 20.92 0 0 1-6.92 1.61 19.76 19.76 0 0 1-4.06-.34 12.6 12.6 0 0 0-4.66-.2c-1.6.3-2.34 4.05-4.45 5.67A.68.68 0 0 1 35 30c-1.79 0-7.22-3.31-6.94-7.53zm23.54-9.15c3.14-2.93 6.59-7.25 9.4-10.13 1.56-1.58 4.58-1.53 7.14-1.48h1.91c5.15-.16 10.32-.07 15.44-.61C87.83.86 92.84-.51 95 .2c.69.24-5.78 4.59-8 5.5a59.59 59.59 0 0 1-18.21 4c-.31.65-3.64 2.5-6.14 2.75 0 0-1.42 2.56-3.66 2.95a.68.68 0 0 1-.2 0c-1.29.05-4.56-1.4-7.19-2.08z"
						></path>
					</svg>
				</div>
			</section>
		</main>
	</div>
</template>

<script>
import Vibrant from 'node-vibrant';
import debounce from 'lodash.debounce';
import NProgress from 'accessible-nprogress';
import VibrantPalette from '@/components/VibrantPalette';
import PlaceholderBlock from '@/components/PlaceholderBlock';
import { randomNorton } from '@/norton';
import {
	descByKey,
	paletteWithContrast,
	resolveUrl,
	urlWithParams,
} from '@/util';

export default {
	name: 'App',
	components: {
		VibrantPalette,
		PlaceholderBlock,
	},
	props: {
		query: {
			type: Object,
		},
	},
	data() {
		return {
			googleBooks: 'https://www.googleapis.com/books/v1/volumes',
			unsplash: 'https://source.unsplash.com/random',
			dimensions: '500x400',
			inputUrl: null,
			resolvedUrl: null,
			validImg: true,
			inputFeedback: null,
			palette: null,
		};
	},
	computed: {
		randomNorton() {
			return randomNorton();
		},
		randomUnsplash() {
			return `${this.unsplash}/${this.dimensions}`;
		},
		accessiblePalette() {
			return this.palette
				? this.palette
						.filter(s => s.contrastColor.contrast >= 4.5)
						.sort(descByKey('population'))
				: {};
		},
		dominantSwatch() {
			return this.palette ? this.accessiblePalette[0] : {};
		},
		dominantStyle() {
			return this.dominantSwatch.css;
		},
		inverseStyle() {
			return this.dominantStyle
				? {
					backgroundColor: this.dominantStyle.color,
					color: this.dominantStyle.backgroundColor,
				}
				: null;
		},
		gradiantStyle() {
			if (this.palette) {
				const rgb = this.dominantSwatch.rgb.join(',');
				return {
					background: `linear-gradient(
              to left,
              rgba(${rgb}, 1),
              rgba(${rgb}, 0)
            )`,
				};
			}
			return {};
		},
		seagullStyle() {
			return {
				fill: this.palette
					? this.palette.find(p => p.name === 'DarkVibrant').hex
					: '#2e445c',
			};
		},
	},
	methods: {
		async loadRandomNorton() {
			if (!this.inputUrl || !this.inputUrl.startsWith(this.googleBooks)) {
				this.inputUrl = await this.randomNorton;
			}
			return this.loadImage(this.inputUrl, true);
		},
		loadRandomUnsplash() {
			if (!this.inputUrl || !this.inputUrl.startsWith(this.unsplash)) {
				this.inputUrl = this.randomUnsplash;
			}
			return this.loadImage(this.inputUrl, true);
		},
		onInput: debounce(function() {
			return this.loadImage(this.inputUrl, true);
		}, 750),
		async loadImage(url, history = false) {
			NProgress.start();
			this.inputUrl = url;
			this.resolvedUrl = await resolveUrl(url);
			if (
				history &&
				window.location.href !==
					window.location.origin + window.location.pathname
			) {
				window.history.pushState({ image: this.resolvedUrl }, '', '/');
			}
			NProgress.inc();
		},
		async processImage(e) {
			try {
				const vibrant = new Vibrant(e.target);
				this.palette = paletteWithContrast(await vibrant.getPalette());
				NProgress.inc();
				this.validImg = true;
				this.inputFeedback = null;
				NProgress.done();
			} catch (err) {
				this.validImg = false;
				this.inputFeedback =
					'The image could not be processed. This is likely a <a href="https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS">CORS</a> issue.';
				NProgress.done();
			}
		},
		loadFromLocation() {
			const { searchParams } = new URL(window.location);
			const image = searchParams.get('image');
			if (image) {
				this.loadImage(image);
			} else {
				this.loadRandomUnsplash();
			}
		},
		copyLink() {
			const { href } = urlWithParams(window.location.origin, {
				image: this.resolvedUrl,
			});
			navigator.clipboard.writeText(href);
		},
	},
	async created() {
		this.loadFromLocation();
		window.addEventListener('popstate', this.loadFromLocation.bind(this));
	},
};
</script>

<style>
.vibrant-figure {
	position: relative;
	display: flex;
	flex-wrap: wrap;
	align-content: stretch;
	margin-bottom: 1.5rem;
}

.vibrant-img {
	position: relative;
	display: block;
	margin: 0 auto;
}

.vibrant-gradient {
	position: absolute;
	left: 0;
	top: 0;
	height: 100%;
	width: 100%;
	z-index: 20;
}

@media screen and (min-width: 768px) {
	.vibrant-img {
		flex: 2 1;
		margin: 0;
	}

	.vibrant-caption {
		flex: 3 1;
	}
}

@media screen and (min-width: 992px) {
	.vibrant-img {
		flex: 4 1;
		margin: 0;
	}

	.vibrant-caption {
		flex: 5 1;
	}
}

.vibrant-caption {
	display: grid;
	padding: 15px;
	z-index: 100;
}

.grid-justify-center {
	justify-self: center;
}

.grid-align-start {
	align-self: start;
}

.svg-seagull {
	margin: 0 0.25em;
	width: 3em;
}
</style>
